export const NavBarList = [
    {id: 1, title: 'Главная', path: '/', ul: []},
    {id: 2, title: 'О больнице', path: '/about', ul: [
            {id: 21, title: 'История стационара', path: '/about/history', ul:[]},
            {id: 22, title: 'О Сергее Ивановиче Спасокукоцком', path: '/about/s-i-spasokukotskij', ul:[]},
            {id: 23, title: 'Сведения о ГКБ им. С.И. Спасокукоцкого', path: '#', ul:[]},
            {id: 24, title: 'Официальные документы', path: '/about/documents', ul:[]},
            {id: 25, title: 'Руководство больницы', path: '/about/administration', ul:[]},
            {id: 26, title: 'Московский врач', path: '/about/moscow-doctor', ul:[]},
            {id: 27, title: 'Кафедры и университетские клиники', path: '/about/university', ul:[]},
            {id: 28, title: 'Вакансии', path: '/about/vacancies', ul:[]},
        ]},
    {id: 3, title: 'Пациентам', path: '/patients', ul: [
            {id: 31, title: 'Госпитализация в стационар', path: '/patients/hospitalization', ul:[]},
            {id: 32, title: 'Диагностика', path: '/patients/research', ul:[]},
            {id: 33, title: 'Пребывание и посещение', path: '/patients/visitors', ul:[
                    {id: 331, title: 'Правила внутреннего распорядка', path: '/patients/visitors', ul:[]},
                    {id: 332, title: 'Посещение пациентов', path: '/patients/visitors', ul:[]},
                    {id: 333, title: 'Правила въезда и парковки', path: '/patients/visitors', ul:[]},
                ]},
            {id: 34, title: 'Полезная информация', path: '/patients/recommendations', ul:[
                    {id: 341, title: 'Памятки пациентам', path: '/patients/recommendations', ul:[]},
                    {id: 342, title: 'Лекарственное обеспечение', path: '#', ul:[]},
                    {id: 343, title: 'Диспансеризация', path: '/patients/examination', ul:[]},
                ]},
            {id: 35, title: 'Иногородним пациентам', path: '/patients/non-residents', ul:[
                    {id: 351, title: 'Медицинский туризм', path: '/patients/tourism', ul:[]},
                    {id: 352, title: 'Москва - столица здоровья', path: '/patients/health-capital', ul:[]},
                    {id: 353, title: 'Иностранным гражданам / For foreign citizens', path: '/patients/tourism', ul:[]},
                ]},
            {id: 36, title: 'Отзывы пациентов', path: '/patients/testimonials', ul:[]},
            {id: 37, title: 'Оставить отзыв о больнице', path: '/patients/feedback', ul:[]},
        ]},
    {id: 4, title: 'Службы и отделения', path: '/cdc', ul: [
            {id: 41, title: 'Консультационно-диагностический центр', path: '/cdc', ul:[]},
        ]},
    {id: 5, title: 'Платные услуги', path: '#', ul: [
            {id:51, title: 'Услуги', path:'/services', ul:[]},
            {id:52, title: 'Специалисты', path:'#', ul:[]},
            {id:53, title: 'Прайс-лист', path:'#', ul:[]},
            {id:54, title: 'Контакты', path:'#', ul:[]},
        ]},
    {id: 6, title: 'Пресс-центр', path: '#', ul: [
            {id:61, title: 'Информация для журналистов и СМИ', path:'/press', ul:[]},
            {id:62, title: 'Новости больницы', path:'/press/news', ul:[]},
            {id:63, title: 'СМИ о нас', path:'/press/media', ul:[]},
            {id:64, title: 'Вопрос-ответ', path:'/patients/faq', ul:[]},
            {id:65, title: 'Фотогалерея', path:'/press/photo', ul:[]},
            {id:66, title: 'Видеогалерея', path:'/press/video', ul:[]},
        ]},
    {id: 7, title: 'Контакты', path: '/contact', ul: [
            {id:71, title: 'Родильный дом', path:'/contact/maternity-hospital', ul:[]},
            {id:72, title: 'Женская консультация №1', path:'/contact/women-consultation-1', ul:[]},
            {id:73, title: 'Женская консультация №2', path:'/contact/women-consultation-2', ul:[]},
            {id:74, title: 'ЖК №3 на Флотской', path:'/contact/women-consultation-3-flotskaya', ul:[]},
            {id:75, title: 'ЖК №3 на Дубровской', path:'/contact/women-consultation-3-dubrovskaya', ul:[]},
            {id:76, title: 'Женская консультация №6', path:'/contact/women-consultation-6', ul:[]},
            {id:77, title: 'ЖК №7 на Борисоглебском', path:'/contact/women-consultation-7-borisoglebsky', ul:[]},
            {id:78, title: 'ЖК №7 на Проспекте Мира', path:'/contact/women-consultation-7-prospekt-mira', ul:[]},
            {id:79, title: 'Женская консультация №12', path:'/contact/women-consultation-12', ul:[]},
            {id:710, title: 'Женская консультация №15', path:'/contact/women-consultation-15', ul:[]},
            {id:711, title: 'Женская консультация №32', path:'/contact/women-consultation-32', ul:[]},
        ]},
]
