export const NavBarList = [
    {id: 1, title: 'Главная', path: '/', ul: []},
    {id: 2, title: 'О больнице', path: '/about', ul: [
            {id: 21, title: 'История стационара', path: '/about/history'},
            {id: 22, title: 'О Сергее Ивановиче Спасокукоцком', path: '/about/s-i-spasokukotskij'},
            {id: 23, title: 'Сведения о ГКБ им. С.И. Спасокукоцкого', path: '#'},
            {id: 24, title: 'Официальные документы', path: '/about/documents'},
            {id: 25, title: 'Руководство больницы', path: '/about/administration'},
            {id: 26, title: 'Московский врач', path: '/about/moscow-doctor'},
            {id: 27, title: 'Кафедры и университетские клиники', path: '/about/university'},
            {id: 28, title: 'Вакансии', path: '/about/vacancies'},
        ]},
    {id: 3, title: 'Пациентам', path: '/patients', ul: [
            {id: 31, title: 'Госпитализация в стационар', path: '/patients/hospitalization'},
            {id: 32, title: 'Диагностика', path: '/patients/research'},
            {id: 33, title: '*Пребывание и посещение', path: '/patients/visitors'},
            {id: 34, title: '*Полезная информация', path: '/patients/recommendations'},
            {id: 35, title: '*Иногородним пациентам', path: '/patients/non-residents'},
            {id: 36, title: 'Отзывы пациентов', path: '/patients/testimonials'},
            {id: 37, title: 'Оставить отзыв о больнице', path: '/patients/feedback'},
        ]},
    {id: 4, title: 'Службы и отделения', path: '/cdc', ul: [
            {id: 41, title: 'Консультационно-диагностический центр', path: '/cdc'},
        ]},
    {id: 5, title: 'Платные услуги', path: '#', ul: [
            {id:51, title: 'Услуги', path:'/services'},
            {id:52, title: 'Специалисты', path:'#'},
            {id:53, title: 'Прайс-лист', path:'#'},
            {id:54, title: 'Контакты', path:'#'},
        ]},
    {id: 6, title: 'Пресс-центр', path: '#', ul: [
            {id:61, title: 'Информация для журналистов и СМИ', path:'/press'},
            {id:62, title: 'Новости больницы', path:'/press/news'},
            {id:63, title: 'СМИ о нас', path:'/press/media'},
            {id:64, title: 'Вопрос-ответ', path:'/patients/faq'},
            {id:65, title: 'Фотогалерея', path:'/press/photo'},
            {id:66, title: 'Видеогалерея', path:'/press/video'},
        ]},
    {id: 7, title: 'Контакты', path: '/contact', ul: [
            {id:71, title: 'Родильный дом', path:'/contact/maternity-hospital'},
            {id:72, title: 'Женская консультация №1', path:'/contact/women-consultation-1'},
            {id:73, title: 'Женская консультация №2', path:'/contact/women-consultation-2'},
            {id:74, title: 'ЖК №3 на Флотской', path:'/contact/women-consultation-3-flotskaya'},
            {id:75, title: 'ЖК №3 на Дубровской', path:'/contact/women-consultation-3-dubrovskaya'},
            {id:76, title: 'Женская консультация №6', path:'/contact/women-consultation-6'},
            {id:77, title: 'ЖК №7 на Борисоглебском', path:'/contact/women-consultation-7-borisoglebsky'},
            {id:78, title: 'ЖК №7 на Проспекте Мира', path:'/contact/women-consultation-7-prospekt-mira'},
            {id:79, title: 'Женская консультация №12', path:'/contact/women-consultation-12'},
            {id:791, title: 'Женская консультация №15', path:'/contact/women-consultation-15'},
            {id:792, title: 'Женская консультация №32', path:'/contact/women-consultation-32'},
        ]},
]
